/**
 * Sample shelf for the signed-out showcase — enough Sichuan-Chongqing saves
 * to open 山城 (4 ≥ OPEN_THRESHOLD) and two Italian saves so the home also
 * demos an under-construction tease. Static demo data; the real app derives
 * from the household's actual shelf.
 */

import type { SavedRecipe } from '@/lib/types';

const base = {
  household_id: 'preview',
  steps: [] as string[],
  provenance: 'transcribed' as const,
  confidence: 'high' as const,
  notes: [] as string[],
  art_url: null,
  art_status: 'none',
  created_at: '2026-07-01T00:00:00Z',
};

export const PREVIEW_SHELF: SavedRecipe[] = [
  {
    ...base,
    id: 'preview-xiaomian',
    source_url: 'https://www.tiktok.com/@mala.queen/video/1',
    source_platform: 'tiktok',
    creator: 'mala.queen',
    title: 'Chongqing xiaomian',
    sub: '重庆小面',
    description: 'The alley noodle — chili oil, numbing tingle, ten-minute ritual.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 2,
    minutes: 20,
    heat: 3,
    ingredients: [
      { name: 'fresh alkaline wheat noodles', quantity: 1, unit: 'lb', pantry: false },
      { name: 'chili crisp', quantity: 1, unit: 'jar', pantry: false },
      { name: 'sichuan peppercorns', quantity: null, unit: null, pantry: true },
      { name: 'baby bok choy', quantity: 1, unit: 'lb', pantry: false },
      { name: 'green onions', quantity: 1, unit: 'bunch', pantry: false },
    ],
  },
  {
    ...base,
    id: 'preview-laziji',
    source_url: 'https://www.instagram.com/p/laziji',
    source_platform: 'instagram',
    creator: 'wok.uncle',
    title: 'Mala chicken',
    sub: '辣子鸡',
    description: 'Crisp chicken buried in a mountain of dried chiles — dig for treasure.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 4,
    minutes: 45,
    heat: 3,
    ingredients: [
      { name: 'chicken thighs', quantity: 2, unit: 'lb', pantry: false },
      { name: 'dried red chiles', quantity: 4, unit: 'oz', pantry: false },
      { name: 'sichuan peppercorns', quantity: null, unit: null, pantry: true },
      { name: 'garlic', quantity: 1, unit: 'head', pantry: false },
      { name: 'ginger', quantity: 1, unit: 'piece', pantry: false },
    ],
  },
  {
    ...base,
    id: 'preview-mapo',
    source_url: 'https://www.youtube.com/watch?v=mapo',
    source_platform: 'youtube',
    creator: 'chef.wang',
    title: 'Mapo tofu',
    sub: '麻婆豆腐',
    description: 'Silken tofu in the bubbling red — doubanjiang doing the talking.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 4,
    minutes: 30,
    heat: 2,
    ingredients: [
      { name: 'silken tofu', quantity: 2, unit: 'each', pantry: false },
      { name: 'ground pork', quantity: 0.5, unit: 'lb', pantry: false },
      { name: 'doubanjiang', quantity: 1, unit: 'jar', pantry: false },
      { name: 'green onions', quantity: 1, unit: 'bunch', pantry: false },
    ],
  },
  {
    ...base,
    id: 'preview-dandan',
    source_url: 'https://www.pinterest.com/pin/dandan',
    source_platform: 'pinterest',
    creator: 'noodle.archive',
    title: 'Dan dan noodles',
    sub: '担担面',
    description: 'Sesame, chili oil, and pork crumble carried on a shoulder pole.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 2,
    minutes: 25,
    heat: 2,
    ingredients: [
      { name: 'fresh wheat noodles', quantity: 1, unit: 'lb', pantry: false },
      { name: 'ground pork', quantity: 0.5, unit: 'lb', pantry: false },
      { name: 'tahini', quantity: 1, unit: 'jar', pantry: false },
      { name: 'chili oil', quantity: null, unit: null, pantry: true },
    ],
  },
  // Two Italian saves — the home teases "2 more and the kitchen opens".
  {
    ...base,
    id: 'preview-cacio',
    source_url: 'https://www.tiktok.com/@pasta.nonna/video/9',
    source_platform: 'tiktok',
    creator: 'pasta.nonna',
    title: 'Cacio e pepe',
    sub: null,
    description: 'Three ingredients, one emulsion, zero forgiveness.',
    cuisine: 'italian',
    dish_type: 'main',
    serves: 2,
    minutes: 20,
    heat: 0,
    ingredients: [
      { name: 'spaghetti', quantity: 1, unit: 'lb', pantry: false },
      { name: 'pecorino romano', quantity: 8, unit: 'oz', pantry: false },
      { name: 'black peppercorns', quantity: null, unit: null, pantry: true },
    ],
  },
  {
    ...base,
    id: 'preview-ragu',
    source_url: 'https://www.instagram.com/p/ragu',
    source_platform: 'instagram',
    creator: 'sunday.sauce',
    title: 'Weeknight ragù',
    sub: null,
    description: 'The Sunday sauce, compressed into a Tuesday.',
    cuisine: 'italian',
    dish_type: 'main',
    serves: 4,
    minutes: 50,
    heat: 0,
    ingredients: [
      { name: 'ground beef', quantity: 1, unit: 'lb', pantry: false },
      { name: 'crushed tomatoes', quantity: 28, unit: 'oz', pantry: false },
      { name: 'rigatoni', quantity: 1, unit: 'lb', pantry: false },
    ],
  },
];
