/**
 * Sample starter catalog for the signed-out showcase — a slice of the real
 * one (the API owns the full deck), just enough to demo the picker's live
 * teaching and the mint moment without a session.
 */

import type { StarterDishWire } from '@/lib/types';

const ING = (name: string, quantity: number | null, unit: string | null, pantry = false) => ({
  name,
  quantity,
  unit,
  pantry,
});

export const PREVIEW_STARTERS: StarterDishWire[] = [
  {
    id: 'xiaomian',
    title: 'Chongqing xiaomian',
    sub: '重庆小面',
    description: 'The alley noodle — chili oil, numbing tingle, ten-minute ritual.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 2,
    minutes: 20,
    heat: 3,
    ingredients: [
      ING('fresh alkaline wheat noodles', 1, 'lb'),
      ING('chili crisp', 1, 'jar'),
      ING('baby bok choy', 1, 'lb'),
      ING('sichuan peppercorns', null, null, true),
    ],
    steps: [],
  },
  {
    id: 'laziji',
    title: 'Chongqing chicken',
    sub: '辣子鸡',
    description: 'Crisp chicken hiding in a mountain of toasted chiles.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 4,
    minutes: 45,
    heat: 3,
    ingredients: [
      ING('boneless chicken thighs', 1.5, 'lb'),
      ING('dried red chiles', 4, 'oz'),
      ING('garlic', 1, 'head'),
    ],
    steps: [],
  },
  {
    id: 'mapo-tofu',
    title: 'Mapo tofu',
    sub: '麻婆豆腐',
    description: 'Silken tofu in the bubbling red — doubanjiang doing the talking.',
    cuisine: 'sichuan-chongqing',
    dish_type: 'main',
    serves: 4,
    minutes: 30,
    heat: 2,
    ingredients: [
      ING('silken tofu', 2, 'each'),
      ING('ground pork', 0.5, 'lb'),
      ING('doubanjiang', 1, 'jar'),
    ],
    steps: [],
  },
  {
    id: 'butter-chicken',
    title: 'Butter chicken',
    sub: 'murgh makhani',
    description: 'The gateway gravy — charred thighs in tomato silk.',
    cuisine: 'indian',
    dish_type: 'main',
    serves: 4,
    minutes: 60,
    heat: 1,
    ingredients: [
      ING('boneless chicken thighs', 2, 'lb'),
      ING('crushed tomatoes', 28, 'oz'),
      ING('heavy cream', 1, 'each'),
    ],
    steps: [],
  },
  {
    id: 'chana-masala',
    title: 'Chana masala',
    sub: null,
    description: 'Chickpeas in a dark, sour-edged gravy — pantry food with a punch.',
    cuisine: 'indian',
    dish_type: 'main',
    serves: 4,
    minutes: 35,
    heat: 2,
    ingredients: [
      ING('canned chickpeas', 2, 'can'),
      ING('yellow onions', 2, 'each'),
      ING('garam masala', null, null, true),
    ],
    steps: [],
  },
  {
    id: 'dal-tadka',
    title: 'Dal tadka',
    sub: null,
    description: 'Yellow lentils finished with a sizzling pour of spiced ghee.',
    cuisine: 'indian',
    dish_type: 'main',
    serves: 4,
    minutes: 40,
    heat: 1,
    ingredients: [
      ING('red lentils', 1, 'lb'),
      ING('ghee', 1, 'jar'),
      ING('cumin seeds', null, null, true),
    ],
    steps: [],
  },
  {
    id: 'breakfast-sandwich',
    title: 'Breakfast sandwich, golden-arches style',
    sub: null,
    description: 'The round egg, the griddled muffin, the exact melt point.',
    cuisine: 'american-comfort',
    dish_type: 'breakfast',
    serves: 4,
    minutes: 15,
    heat: null,
    ingredients: [
      ING('english muffins', 1, 'pack'),
      ING('large eggs', 1, 'dozen'),
      ING('canadian bacon', 1, 'pack'),
    ],
    steps: [],
  },
  {
    id: 'smash-burger',
    title: 'Smash burger',
    sub: null,
    description: 'Thin patties smashed hard, edges like lace.',
    cuisine: 'american-comfort',
    dish_type: 'main',
    serves: 4,
    minutes: 25,
    heat: null,
    ingredients: [
      ING('ground beef 80/20', 1.5, 'lb'),
      ING('american cheese slices', 1, 'pack'),
      ING('sesame hamburger buns', 1, 'pack'),
    ],
    steps: [],
  },
  {
    id: 'crispy-chicken-sandwich',
    title: 'Crispy chicken sandwich',
    sub: null,
    description: 'Buttermilk-brined thigh, shattering crust, pickles talking.',
    cuisine: 'american-comfort',
    dish_type: 'main',
    serves: 4,
    minutes: 45,
    heat: 1,
    ingredients: [
      ING('boneless chicken thighs', 2, 'lb'),
      ING('buttermilk', 1, 'each'),
      ING('dill pickles', 1, 'jar'),
    ],
    steps: [],
  },
];
